### ISSUE TITLE
Adding Support for hiding Vulnerability Description

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp-facade#51]
As shown in the below image, there is no way to hide the Vulnerability Description in the page.

![image](https://user-images.githubusercontent.com/13570884/134777323-47e0a986-97f6-44bf-98ef-e8895f3cb352.png)

In this task we are looking for a way to hide and unhide the Vulnerability Description, similar to the way we hide the hint on the page.

Code reference:
https://github.com/SasanLabs/VulnerableApp-facade/blob/main/facade-app/src/Components/Content.tsx#L95

**Comment by Duy-L** [comment]
if the problem still exists, can I tackle this?

**Comment by preetkaran20** [comment]
Hi @Duy-L ,

Yes, the problem exists. I have assigned the issue to you.

thanks,
Karan

**Comment by preetkaran20** [comment]
Thanks a lot, @Duy-L.

As you have already done setup the VulnerableApp, any feedback is appreciated. Also please raise the issue or send an email to karan.sasan@owasp.org, if you feel something is not working correctly or some enhancement that can benefit the project.
