### ISSUE TITLE
UI expands if data is more on the screen

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp-facade#54]
Navigate to JWT Vulnerability UI screen and fetch the token for level 2 or level 3 and you will see that the X-Axis becomes expanded. we need to wrap the text such that the UI doesn't become distorted.

![image](https://user-images.githubusercontent.com/13570884/149754467-4c3eccd8-8d7c-4db8-82f4-7c62ffafacf4.png)
![image](https://user-images.githubusercontent.com/13570884/149754537-1d325374-e916-470e-8cd3-66a0c2b2188b.png)

**Comment by sidd-oo** [comment]
Hey @preetkaran20 
I am interested in working on this issue. Can you please assign it to me?
