### ISSUE TITLE
Add unit tests for Utils.ts file

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp-facade#88]
As part of https://github.com/SasanLabs/VulnerableApp-facade/issues/56 we have introduced a unit testing framework and now we are looking for adding more unit test for the project.

we are missing unit tests for https://github.com/SasanLabs/VulnerableApp-facade/blob/main/facade-app/src/Utilities/Utils.ts file.

Have a look at codecov report for finding what all is missing and cover that as part of this issue.
Codecov report: https://app.codecov.io/gh/SasanLabs/VulnerableApp-facade/tree/main/facade-app/src/Utilities

**Comment by amrendranath** [comment]
hi @preetkaran20 I would like to work on this issue. Can you assign it to me?

**Comment by preetkaran20** [comment]
Hi @amrendranath , 

Sure

**Comment by preetkaran20** [comment]
closing issue as already handled by @amrendranath in #92
