### ISSUE TITLE
Add unit test for App.tsx

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp-facade#89]
As part of https://github.com/SasanLabs/VulnerableApp-facade/issues/56 we have introduced a unit testing framework and now we are looking for adding more unit test for the project.

we are missing unit tests for https://github.com/SasanLabs/VulnerableApp-facade/blob/main/facade-app/src/App.tsx file

Have a look at codecov report for finding what all is missing and cover that as part of this issue.
Codecov report: https://app.codecov.io/gh/SasanLabs/VulnerableApp-facade/blob/main/facade-app/src/App.tsx

**Comment by lejara** [comment]
Hello!

May i take this on?

**Comment by preetkaran20** [comment]
Hi @lejara , 

Sure.

**Comment by preetkaran20** [comment]
Thank you !!!
